---
- hosts: sonar
  become: true
  vars:
    sonar_version: 8.9.7.52159
  pre_tasks:
    - name: Install package dependencies.
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - unzip
        - default-jdk
  
  roles:
    - lrk.sonarqube