---
- hosts: akeem
  become: true
  vars:
    service_name: docker 
  # roles:
  #  - tools
  #  - deploy
  tasks:
    - name: copy docker-compose
      copy:
        src: ./docker-compose.yml
        dest: /docker-compose.yml
    - name: run application
      shell: cd / && docker-compose up -d 