- hosts: ihab
  tasks:
    - name: sauvegarde des base de données mysql
      shell: "mysqldump -h {{item.remote}} -u {{item.user}} -p{{password}} {{item.basename}} > backup/{{item.basename}}.sql"
      with_items:
      - { user: 'nom_utilisateur', basename: 'nom_base_de_donnees', remote: 'localhost'}
      - { user: '', basename: '', remote: ''}
      - { user: '', basename: '', remote: ''}
      - { user: '', basename: '', remote: ''}
    - name: fetch
      synchronize: src=backup dest=backup/ mode=pull